### PR TITLE
Updated log in and browse layouts

### PR DESCRIPTION
**Pull request by rhodesrm**
Updated log in, browse, and view profile buttons and text layout

### CODE REVIEW

**Review by gallettilance — CHANGES_REQUESTED** [review]
Can you fix the bugs so that the CI passed? (It will have to do with the positioning in the layout - but basically anywhere in Android Studio that is underlined in red). When you commit your changes and you notice that the red X becomes a green check it means you have fixed all the bugs. Feel free to make as many commits as you need - I will keep this PR open. Thank you!

**Comment by gallettilance** [comment]
@rhodesrm what's the status on this?

**Comment by rhodesrm** [comment]
@galletti94 I fixed the issues, however I'm having trouble submitting a pull request after committing to my branch

**Comment by gallettilance** [comment]
@rhodesrm I left the pull request open so that any commit you made on your fork would automatically merge into this pull request :) Thank you for the fixes! Will merge now

**Comment by gallettilance** [comment]
@rhodesrm actually not all checks have passed (notice the red x on your commits). Please double check that you have no red error lines in android studio.

**Comment by rhodesrm** [comment]
@galletti94 It says the build passed after the last fix,  so I think it's good. If you're seeing something different on your end, let me know. Thanks!

**Pull request merged**
